INSERT INTO users (name, email) VALUES
    ('Rahul',    'rahul123@gmail.com'),
    ('Abhishek', 'abhi9@gmail.com'),
    ('Aman',     'aman415@gmail.com'),
    ('Sarada',   'sard85@gmail.com'),
    ('Priya',    'priya22@gmail.com'),
    ('Rohan',    'rohan77@gmail.com'),
    ('Neha',     'neha.k@gmail.com'),
    ('Vikram',   'vikram99@gmail.com'),
    ('Kiran',    'kiran55@gmail.com'),
    ('Divya',    'divya33@gmail.com');

INSERT INTO todo (title, description, priority, user_id, status) VALUES
    ('Task 1',  'Description 1',  'Low',    1, 'Pending'),
    ('Task 2',  'Description 2',  'Medium', 2, 'In Progress'),
    ('Task 3',  'Description 3',  'High',   3, 'Completed'),
    ('Task 4',  'Description 4',  'Low',    4, 'Pending'),
    ('Task 5',  'Description 5',  'Medium', 5, 'In Progress'),
    ('Task 6',  'Description 6',  'High',   6, 'Completed'),
    ('Task 7',  'Description 7',  'Low',    7, 'Pending'),
    ('Task 8',  'Description 8',  'Medium', 8, 'In Progress'),
    ('Task 9',  'Description 9',  'High',   9, 'Completed'),
    ('Task 10', 'Description 10', 'Low',    10,'Pending'),
    ('Task 11', 'Description 11', 'Medium', 1, 'In Progress'),
    ('Task 12', 'Description 12', 'High',   2, 'Completed'),
    ('Task 13', 'Description 13', 'Low',    3, 'Pending'),
    ('Task 14', 'Description 14', 'Medium', 4, 'In Progress'),
    ('Task 15', 'Description 15', 'High',   5, 'Completed'),
    ('Task 16', 'Description 16', 'Low',    6, 'Pending'),
    ('Task 17', 'Description 17', 'Medium', 7, 'In Progress'),
    ('Task 18', 'Description 18', 'High',   8, 'Completed'),
    ('Task 19', 'Description 19', 'Low',    9, 'Pending'),
    ('Task 20', 'Description 20', 'Medium', 10,'In Progress'),
    ('Task 21', 'Description 21', 'High',   1, 'Completed'),
    ('Task 22', 'Description 22', 'Low',    2, 'Pending'),
    ('Task 23', 'Description 23', 'Medium', 3, 'In Progress'),
    ('Task 24', 'Description 24', 'High',   4, 'Completed'),
    ('Task 25', 'Description 25', 'Low',    5, 'Pending'),
    ('Task 26', 'Description 26', 'Medium', 6, 'In Progress'),
    ('Task 27', 'Description 27', 'High',   7, 'Completed'),
    ('Task 28', 'Description 28', 'Low',    8, 'Pending'),
    ('Task 29', 'Description 29', 'Medium', 9, 'In Progress'),
    ('Task 30', 'Description 30', 'High',   10,'Completed'),
    ('Task 31', 'Description 31', 'Low',    1, 'Pending'),
    ('Task 32', 'Description 32', 'Medium', 2, 'In Progress'),
    ('Task 33', 'Description 33', 'High',   3, 'Completed'),
    ('Task 34', 'Description 34', 'Low',    4, 'Pending'),
    ('Task 35', 'Description 35', 'Medium', 5, 'In Progress'),
    ('Task 36', 'Description 36', 'High',   6, 'Completed'),
    ('Task 37', 'Description 37', 'Low',    7, 'Pending'),
    ('Task 38', 'Description 38', 'Medium', 8, 'In Progress'),
    ('Task 39', 'Description 39', 'High',   9, 'Completed'),
    ('Task 40', 'Description 40', 'Low',    10,'Pending'),
    ('Task 41', 'Description 41', 'Medium', 1, 'In Progress'),
    ('Task 42', 'Description 42', 'High',   2, 'Completed'),
    ('Task 43', 'Description 43', 'Low',    3, 'Pending'),
    ('Task 44', 'Description 44', 'Medium', 4, 'In Progress'),
    ('Task 45', 'Description 45', 'High',   5, 'Completed'),
    ('Task 46', 'Description 46', 'Low',    6, 'Pending'),
    ('Task 47', 'Description 47', 'Medium', 7, 'In Progress'),
    ('Task 48', 'Description 48', 'High',   8, 'Completed'),
    ('Task 49', 'Description 49', 'Low',    9, 'Pending'),
    ('Task 50', 'Description 50', 'Medium', 10,'In Progress');