"""add stats table with cascade

Revision ID: 262d78572e99
Revises: 
Create Date: 2026-06-06 15:39:17.085467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262d78572e99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stats_urlCode_fkey'), 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'shorten_url', ['urlCode'], ['urlCode'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(op.f('stats_urlCode_fkey'), 'stats', 'shorten_url', ['urlCode'], ['urlCode'])
    # ### end Alembic commands ###
